### ISSUE TITLE
感谢分享！

### ISSUE THREAD

**Issue by lanmingle** [BurdenBear/kube-charts-mirror#3]
另外分享一个：https://github.com/lanmingle/docker-desktop-for-mac-in-kubernetes

**Comment by donggangcj** [comment]
很棒！:blush:

**Comment by pureboys** [comment]
感谢分享！  貌似azure也提供了镜像。
stable   	 http://mirror.azure.cn/kubernetes/charts/
incubator	 http://mirror.azure.cn/kubernetes/charts-incubator/

**Comment by lanmingle** [comment]
@pureboys 嘿嘿就用这个了

**Comment by BurdenBear** [comment]
@pureboys  优秀！感谢分享
