### ISSUE TITLE
不能添加repo ,有错

### ISSUE THREAD

**Issue by codwd** [BurdenBear/kube-charts-mirror#4]
Error: Looks like "https://burdenbear.github.io/kube-charts-mirror/" is not a valid chart repository or cannot be reached: Get https://burdenbear.github.io/kube-charts-mirror/index.yaml: proxyconnect tcp: net/http: TLS handshake timeout

**Comment by BurdenBear** [comment]
应该只是因为网络原因，试试关掉代理软件。

**Comment by BurdenBear** [comment]
close it

**Comment by codwd** [comment]
还是不能连接

**Comment by cobb-tx** [comment]
我这边一开始也用的好好的，突然也报错
helm init -c --stable-repo-url http://mirror.azure.cn/kubernetes/charts/
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: http://mirror.azure.cn/kubernetes/charts/ 
WARNING: Deprecated index file format. Try 'helm repo update'
Error: error initializing: Looks like "http://mirror.azure.cn/kubernetes/charts/" is not a valid chart repository or cannot be reached: no API version specified
初始化helm失败

**Comment by stevenkitter** [comment]
Error: looks like "http://mirror.azure.cn/kubernetes/charts-incubator/" is not a valid chart repository or cannot be reached: no API version specified
