### ISSUE TITLE
感谢大佬分享，然后想问个问题

### ISSUE THREAD

**Issue by ode233** [BurdenBear/kube-charts-mirror#5]
![image](https://user-images.githubusercontent.com/36733129/49788274-e3c92500-fd63-11e8-904b-5055d9ea5d12.png)
上面是指令
![image](https://user-images.githubusercontent.com/36733129/49788327-078c6b00-fd64-11e8-96d0-9372f2864b4c.png)
然后好像还是找不到 怎么办呢。。 要用helm装gitlab-runner

**Comment by BurdenBear** [comment]
本项目默认是下载的helm官方charts仓库地址的镜像，地址: https://kubernetes-charts.storage.googleapis.com/
gitlab-runner似乎并不在此仓库下。
当然稍加修改之后你可以自己搭建任意一个charts仓库的镜像。
你可以新建一个自己的项目，将本项目中除docs文件夹以外的内容拷贝过去，修改程序启动时的`CHARTS_URL`环境变量的值为你需要拷贝的charts仓库地址，例如gitlab-runner，根据其文档说明是在: https://charts.gitlab.io
以使用docker启动为例：
```
docker build -t kube-charts-updater .
docker run \
-e GIT_REPO=https://BurdenBear:XXX@github.com/BurdenBear/kube-charts-mirror.git \ 
-e GIT_USER_NAME=BurdenBear \ 
-e GIT_USER_EMAIL=burdenbear@fxdayu.com  \
-e CHARTS_URL=https://charts.gitlab.io
-v /data/charts:/mnt/charts -d kube-charts-updater
```
每次启动都需要指定一致的CHARTS_URL环境变量，建议用docker-compose的启动方式:
参考 #2  
最后在你的项目settings里设置开启gitPage，定位到master分支下的docs文件夹。
glhf

**Comment by ode233** [comment]
> 本项目默认是下载的helm官方charts仓库地址的镜像，地址: https://kubernetes-charts.storage.googleapis.com/
> gitlab-runner似乎并不在此仓库下。
> 当然稍加修改之后你可以自己搭建任意一个charts仓库的镜像。
> 你可以新建一个自己的项目，将本项目中除docs文件夹以外的内容拷贝过去，修改程序启动时的`CHARTS_URL`环境变量的值为你需要拷贝的charts仓库地址，例如gitlab-runner，根据其文档说明是在: https://charts.gitlab.io
> 以使用docker启动为例：
> 
> ```
> docker build -t kube-charts-updater .
> docker run \
> -e GIT_REPO=https://BurdenBear:XXX@github.com/BurdenBear/kube-charts-mirror.git \ 
> -e GIT_USER_NAME=BurdenBear \ 
> -e GIT_USER_EMAIL=burdenbear@fxdayu.com  \
> -e CHARTS_URL=https://charts.gitlab.io
> -v /data/charts:/mnt/charts -d kube-charts-updater
> ```
> 每次启动都需要指定一致的CHARTS_URL环境变量，建议用docker-compose的启动方式:
> 参考 #2
> 最后在你的项目settings里设置开启gitPage，定位到master分支下的docs文件夹。
> glhf

嗯，先谢谢大佬了  helm还不太熟 我再看看

**Comment by ode233** [comment]
> 本项目默认是下载的helm官方charts仓库地址的镜像，地址: https://kubernetes-charts.storage.googleapis.com/
> gitlab-runner似乎并不在此仓库下。
> 当然稍加修改之后你可以自己搭建任意一个charts仓库的镜像。
> 你可以新建一个自己的项目，将本项目中除docs文件夹以外的内容拷贝过去，修改程序启动时的`CHARTS_URL`环境变量的值为你需要拷贝的charts仓库地址，例如gitlab-runner，根据其文档说明是在: https://charts.gitlab.io
> 以使用docker启动为例：
> 
> ```
> docker build -t kube-charts-updater .
> docker run \
> -e GIT_REPO=https://BurdenBear:XXX@github.com/BurdenBear/kube-charts-mirror.git \ 
> -e GIT_USER_NAME=BurdenBear \ 
> -e GIT_USER_EMAIL=burdenbear@fxdayu.com  \
> -e CHARTS_URL=https://charts.gitlab.io
> -v /data/charts:/mnt/charts -d kube-charts-updater
> ```
> 每次启动都需要指定一致的CHARTS_URL环境变量，建议用docker-compose的启动方式:
> 参考 #2
> 最后在你的项目settings里设置开启gitPage，定位到master分支下的docs文件夹。
> glhf

后来又弄了下好像还是有问题。因为现在我是用gitlab集成了k8s，gitlab默认用helm安装应用，他是已经配置好了脚本自动装的，我要去修改感觉有点麻烦而且也不知道去哪改。所以感觉可能还是要翻墙，而且必须是在k8s部署的容器内翻。然后我发现用docker可以直接配置代理，在运行容器时，容器自动走代理端口。但是问题来了，弄了半天我发现k8s部署容器时，他不会用docker客户端的配置，而是使用自己的api (https://stackoverflow.com/questions/52191439/kubernetes-docker-containers-behind-proxy)  
所以僵住了。。。不知道有啥办法没

**Comment by BurdenBear** [comment]
听你的意思是你的gitlab也是以容器的方式在k8s集群里运行吗？启动gitlab容器时直接设置HTTP_PROXY等几个关于代理的环境变量应该就可以了吧；要是用的shadowsock之类的在gitlab镜像里装个python，安下python的shadowsockclient配合设置环境变量一起应该就可以翻墙了。容器里到代理机ip的网络要是走不通就用k8s的service里的externalIP方式打通一下。
