### ISSUE TITLE
使用 azure 中国的镜像可能是一个更好的选择

### ISSUE THREAD

**Issue by lizebang** [BurdenBear/kube-charts-mirror#6]
@BurdenBear 
下面是 azure 中国的镜像网址：
http://mirror.azure.cn/kubernetes/charts/
你可以先测试一下。
我想如果可以，请可以把它加到 README 中，让更多的人受益。

**Comment by BurdenBear** [comment]
使用微软的源比较好，已添加README，感谢分享！ #7
